-keepattributes Signature
-keepattributes EnclosingMethod
-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.stream.** { *; }
-keep class com.google.gson.annotations.** { *; }
-keep class com.google.gson.examples.android.model.** { *; }
-keepnames class * implements com.google.gson.JsonDeserializer
